"""Added job recommendation fields

Revision ID: 0747e50f9d9f
Revises: e6f533be0f2d
Create Date: 2025-04-04 11:42:25.744192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0747e50f9d9f'
down_revision = 'e6f533be0f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apply_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('keywords', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('job_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_recommendations', schema=None) as batch_op:
        batch_op.drop_column('job_id')
        batch_op.drop_column('keywords')
        batch_op.drop_column('apply_link')

    # ### end Alembic commands ###
